# Training a XResnet

In [ ]:
from spanda.data.load import (SpectraBlock, get_spectra_files,
                              get_target, random_weighted_avg)

from pathlib import Path
from fastai.vision.all import *
from fastai.data.all import *

In [ ]:
#|eval: false
path = Path('../../_data/kssl-mirs')
fnames = path.ls(); fnames

(#44101) [Path('../../_data/kssl-mirs/180338'),Path('../../_data/kssl-mirs/172221'),Path('../../_data/kssl-mirs/177753'),Path('../../_data/kssl-mirs/184798'),Path('../../_data/kssl-mirs/53759'),Path('../../_data/kssl-mirs/74947'),Path('../../_data/kssl-mirs/176681'),Path('../../_data/kssl-mirs/1855'),Path('../../_data/kssl-mirs/175004'),Path('../../_data/kssl-mirs/34499')...]

In [ ]:
# Selecting only Kex > 0 values
fnames = L(filter(lambda x: get_target(x, analytes=[725]).item() > 0, fnames)); fnames

(#42443) [Path('../../_data/kssl-mirs/180338'),Path('../../_data/kssl-mirs/172221'),Path('../../_data/kssl-mirs/177753'),Path('../../_data/kssl-mirs/184798'),Path('../../_data/kssl-mirs/53759'),Path('../../_data/kssl-mirs/74947'),Path('../../_data/kssl-mirs/176681'),Path('../../_data/kssl-mirs/1855'),Path('../../_data/kssl-mirs/175004'),Path('../../_data/kssl-mirs/34499')...]

In [ ]:
dblock = DataBlock(
    blocks=(SpectraBlock, RegressionBlock),
    get_x=get_spectra_files,
    get_y=partial(get_target, analytes=[725]),
    splitter=RandomSplitter(valid_pct=0.1, seed=42),
    item_tfms=[Transform(random_weighted_avg)]
)

In [ ]:
torch.cuda.is_available()

False

In [ ]:
dls = dblock.dataloaders(fnames, bs=16)

In [ ]:
dls.train.one_batch()

(tensor([[[0.4312, 0.4317, 0.4322,  ..., 2.0138, 2.0103, 2.0064]],
 
         [[0.1300, 0.1304, 0.1308,  ..., 1.3012, 1.2940, 1.2885]],
 
         [[0.2957, 0.2961, 0.2966,  ..., 1.6344, 1.6192, 1.6056]],
 
         ...,
 
         [[0.3521, 0.3525, 0.3529,  ..., 1.7068, 1.6987, 1.6907]],
 
         [[0.1470, 0.1472, 0.1473,  ..., 1.3141, 1.2980, 1.2837]],
 
         [[0.1730, 0.1734, 0.1738,  ..., 1.5488, 1.5458, 1.5439]]]),
 tensor([[0.6347],
         [0.1577],
         [0.3911],
         [0.3052],
         [1.1182],
         [0.3986],
         [1.0600],
         [0.1405],
         [0.1490],
         [0.1522],
         [0.9625],
         [2.0773],
         [0.5722],
         [0.1186],
         [0.1491],
         [0.3649]]))

In [ ]:
tst = xresnet101(ndim=1, c_in=1, ks=3, n_out=1)

In [ ]:
dls.train.one_batch()[0]

tensor([[[ 0.1985,  0.1986,  0.1988,  ...,  1.4719,  1.4645,  1.4592]],

        [[-0.0814, -0.0811, -0.0809,  ...,  1.2928,  1.3014,  1.3106]],

        [[ 0.1921,  0.1923,  0.1926,  ...,  1.4904,  1.4859,  1.4832]],

        ...,

        [[ 0.3154,  0.3161,  0.3167,  ...,  1.6129,  1.5995,  1.5859]],

        [[ 0.1721,  0.1728,  0.1735,  ...,  1.6604,  1.6430,  1.6262]],

        [[ 0.0830,  0.0831,  0.0832,  ...,  1.1658,  1.1663,  1.1684]]])

In [ ]:
%time tst(dls.train.one_batch()[0])

CPU times: user 46.4 s, sys: 2.59 s, total: 49 s
Wall time: 8.74 s


TensorBase([[0.2961],
            [0.2639],
            [0.3844],
            [0.2930],
            [0.0802],
            [0.1785],
            [0.2784],
            [0.1706],
            [0.0262],
            [0.2320],
            [0.4701],
            [0.1745],
            [0.0791],
            [0.4603],
            [0.3007],
            [0.2933]], grad_fn=<AliasBackward0>)